services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678" # Expose n8n directly on port 5678
    environment:
      # Replace with your actual domain or IP if not using Nginx for external access
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
      - NODE_ENV=${NODE_ENV:-production}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Asia/Bangkok}
      # Basic Auth (highly recommended for security)
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      # Database (Uncomment and configure for PostgreSQL in production)
      # - DB_TYPE=postgresdb
      # - DB_POSTGRESDB_HOST=postgresql
      # - DB_POSTGRESDB_DATABASE=n8n
      # - DB_POSTGRESDB_USER=n8n
      # - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
    networks:
      - n8n_network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # Consider adding SSL certificate volumes here
      # - ./path/to/your/certs:/etc/nginx/certs:ro
    networks:
      - n8n_network
    depends_on:
      - n8n

volumes:
  n8n_data:

networks:
  n8n_network:
    driver: bridge